/*
 * The Fumadocs loader plugin for the API reference generated by the `fumero` CLI.
 *
 * Written by: fumero init <directory>
 *
 * This one registers on the loader rather than in mdx-components.tsx. It works on the page tree the
 * sidebar is built from and never renders a page:
 *
 *   // src/lib/source.ts
 *   import { fumeroPlugin } from '@/components/mdx/pdx-plugin';
 *
 *   export const source = loader({
 *     plugins: [fumeroPlugin()],
 *     baseUrl: '/',
 *     source: docs.toFumadocsSource(),
 *   });
 *
 * Generated pages carry what this reads under one `_fumero` key, and Fumadocs keeps only the
 * frontmatter its schema names, so let that key through:
 *
 *   // source.config.ts
 *   schema: pageSchema.loose(),
 *
 * Or name the key, to have it typed:
 * `pageSchema.extend({ _fumero: z.record(z.string(), z.custom()).optional() })`.
 *
 * Everything fumero carries into the page tree arrives under that one key, so this is the only schema
 * edit there will be.
 *
 * All it does today is label each sidebar entry with the kind of page it leads to. Without it the
 * pages render as they otherwise would, and the sidebar says nothing about kinds.
 *
 * Design
 * ------
 * The label is the kind in lower case, with no box around it. Lower case, because `module` and
 * `class` are the words Python uses.
 *
 * Only the modules take a colour. A module is a branch point, and there are a few of them among many
 * classes, so a green word marks where the tree opens and agrees with the indentation. Colouring the
 * classes too puts the same word at the same place on every row, in a column that reads across the
 * indentation rather than with it, and the tree goes with it. The class label recedes instead, dim
 * enough to sit under the name it belongs to.
 *
 * Alignment
 * ---------
 * The labels read as a column, so they have to land in one. Two things get in the way, and both are
 * handled by the row rather than by the label, which leaves a label passed to `renderLabel` nothing
 * to know about either.
 *
 * A module holding pages is a folder, and a folder's row ends in the chevron that opens it. Pushing
 * the label over with `ms-auto`, the way Fumadocs does on a sidebar of leaf pages, breaks the moment
 * one of those is in the row: free space is shared out between every automatic margin, so a label
 * next to a chevron is left stranded halfway along the row. The name takes the free space here
 * instead, and the label simply follows it.
 *
 * That leaves the chevron itself, which would push a folder's label one column in from every other
 * label. So every row reserves the width of one, and a row that turns out to have a chevron gives the
 * reservation back. The chevrons end up in a column of their own.
 *
 * The page tree names the breadcrumb and the previous/next links too, and a label pushed to the end
 * of a row means nothing in either, so the row folds away to `display: contents` outside the
 * sidebar and takes the label with it.
 */
import type { LoaderPlugin } from 'fumadocs-core/source';
import type { ReactNode } from 'react';

/**
 * What to call each kind of page, and how the label is set apart. A kind absent from here goes
 * unlabelled.
 *
 * The module tint is `-600` on light against `-400` on dark, as Fumadocs tints its own labels.
 */
const KINDS: Record<string, { label: string; className: string } | undefined> = {
  module: { label: 'module', className: 'text-green-600 dark:text-green-400' },
  class: { label: 'class', className: 'text-fd-muted-foreground/60' },
};

/** Outside the sidebar the row is not a row, so it stops being one. */
const SIDEBAR_ONLY = 'not-in-[#nd-sidebar]:contents';

/**
 * The name and its label. `pe-6` is the column a folder's chevron sits in, held open on the rows
 * that have no chevron to put there, and handed back by rows that do.
 */
const ROW = `fd-page-tree-item-name pe-6 [&:has(+[data-icon])]:pe-0 ${SIDEBAR_ONLY}`;

/** Takes the width the label does not, so a name too long for the sidebar is cut rather than it. */
const NAME = `flex-1 truncate ${SIDEBAR_ONLY}`;

/** Tinted rather than boxed, and never squeezed by a long name. */
const BADGE = 'shrink-0 font-mono text-xs not-in-[#nd-sidebar]:hidden';

/**
 * The kind a page claims to be, from the `_fumero` its frontmatter carries.
 *
 * Read defensively rather than trusted: a page tree is built from whatever is on disk, and a
 * hand-edited page or one left behind by an older fumero is not worth a build failure.
 */
function pageKind(meta: unknown): string | undefined {
  if (typeof meta !== 'object' || meta === null || !('kind' in meta)) return;

  return typeof meta.kind === 'string' ? meta.kind : undefined;
}

/** The kind of page one sidebar entry leads to, or nothing for a kind that goes unlabelled. */
export function PdxKind({ kind }: { kind: string }) {
  const labelled = KINDS[kind];
  if (!labelled) return null;

  return <span className={`${BADGE} ${labelled.className}`}>{labelled.label}</span>;
}

/**
 * Label the sidebar entries leading to a generated page with the kind of thing it documents.
 *
 * Pass `renderLabel` to word or style the label differently, to label a kind this does not, or to
 * return nothing for one it does.
 */
export function fumeroPlugin(
  options: { renderLabel?: (kind: string) => ReactNode } = {},
): LoaderPlugin {
  const { renderLabel = (kind) => <PdxKind kind={kind} /> } = options;

  return {
    name: 'fumero',
    transformPageTree: {
      file(node, filePath) {
        if (!filePath) return node;

        const file = this.storage.read(filePath);
        if (file?.format !== 'page' || !('_fumero' in file.data)) return node;

        const kind = pageKind(file.data._fumero);
        if (!kind) return node;

        const label = renderLabel(kind);
        if (!label) return node;

        // a folder takes its name from the page indexing it, so labelling the index labels the
        // module's own row in the tree as well as the page it links to.
        //
        // keyed because Fumadocs renders a row as `[icon, name]`, and an element in a list without
        // a key is a React warning in development.
        node.name = (
          <span key="pdx-kind" className={ROW}>
            <span className={NAME}>{node.name}</span>
            {label}
          </span>
        );

        return node;
      },
    },
  };
}
