/*
 * MDX components for the API reference generated by the `fumero` CLI.
 *
 * Written by: fumero init <path>
 *
 * Register them in your mdx-components.tsx:
 *
 *   import * as Pdx from '@/components/mdx/pdx';
 *   export function getMDXComponents(components) {
 *     return { ...defaultMdxComponents, ...Pdx, ...components };
 *   }
 *
 * These are React Server Components (they syntax-highlight on the server). Every type that has a
 * documentation page becomes a link: the CLI passes a `links` map ({ TypeName: href }) alongside
 * each type string.
 *
 * Design
 * ------
 * Reference documentation is read by someone looking one thing up, not browsing, so the page is
 * built to be scanned: monospace for anything you could type, prose for anything you read, and a
 * hairline wherever one thing ends and the next begins.
 *
 * Colour is reserved for links. Nothing else earns it. A badge tinted green says no more than the
 * word `func` does, and a page full of tinted badges makes the one thing that *is* actionable, a
 * reference to another symbol, harder to pick out. Kind, grouping and hierarchy are carried by
 * weight, size and space instead.
 *
 * Labels are stated once per group rather than once per row. A list of parameters is already a
 * list of parameters; tagging every row `param` repeats what the caption above it just said.
 *
 * Everything reads from the host app's theme tokens (`fd-*`), so the reference tracks the rest of
 * the site in both light and dark with no palette of its own to define or keep in step.
 *
 * Syntax highlighting
 * -------------------
 * Types and default values go through `highlight` from fumadocs-core, which is Shiki. That is
 * where the colour in a type comes from, and it costs no client JavaScript because this all
 * renders on the server. Only these inline fragments are highlighted here. Fenced code blocks in
 * docstrings are plain markdown, highlighted by the host app's own MDX pipeline.
 *
 * Two things are worth knowing before editing `InlineCode`, because both are easy to trip over:
 *
 *   1. The output carries the `.shiki` class, which is the same hook the host app styles its code
 *      *blocks* with. That styling pads every `.line` by 1rem on each side. On a block that is
 *      gutter; on a type sitting inline it is a hole. `InlineCode` cancels it by zeroing
 *      `--padding-left` / `--padding-right`, the custom properties the padding is built from.
 *
 *   2. The colour is applied by CSS, not by the highlighter. Shiki emits only `--shiki-light` and
 *      `--shiki-dark` variables per token; a rule keyed on that same `.shiki` selector turns them
 *      into `color`. So the obvious way to kill the padding, the `not-fumadocs-codeblock` opt-out
 *      those rules are written against, also unpaints every token. Go through the variables.
 *
 * `TypeToken` runs over the highlighted tokens and turns any name found in the `links` map into a
 * link, splicing it into the token's text so the surrounding highlight survives.
 *
 * Portions derived from fumadocs-python, MIT License, Copyright (c) 2023 Fuma Nama. fumero is
 * an independent project, not affiliated with or endorsed by Fumadocs.
 */
import * as React from 'react';
import Link from 'fumadocs-core/link';
import { highlight } from 'fumadocs-core/highlight';
import { Collapsible, CollapsibleContent, CollapsibleTrigger } from 'fumadocs-ui/components/ui/collapsible';
import { ChevronRight } from 'lucide-react';

export { Tab, Tabs } from 'fumadocs-ui/components/tabs';

type Links = Record<string, string>;

function cn(...parts: Array<string | false | undefined>): string {
  return parts.filter(Boolean).join(' ');
}

/** The card a documented member sits in. One border, no fill of its own. */
const CARD = 'my-5 overflow-hidden rounded-lg border border-fd-border bg-fd-card';

/** A member's name, and the thing to find when scanning a page. */
const NAME = 'shrink-0 font-mono text-[13px] font-semibold text-fd-foreground';

/**
 * The caption over a group of rows: `parameters`, `returns`.
 *
 * Unlike the kind label, this one is a landmark, what you look for when you jump into the middle
 * of a long card, so it carries weight and near-foreground contrast. Still no colour: it
 * is the rule above it and the space around it that make the section, and the word only has to
 * name it.
 */
const CAPTION = 'font-mono text-[11px] font-semibold text-fd-foreground/75';

/** Type annotations, defaults, and anything else you could paste back into an editor. */
const CODE = 'font-mono text-xs text-fd-muted-foreground';

/**
 * Overflow without truncation. An ellipsis silently eats the tail of a type; scrolling keeps every
 * character reachable and stays on one line. The scrollbar is hidden because it would sit inside
 * the row on platforms that reserve space for it.
 */
const SCROLL = 'min-w-0 overflow-x-auto whitespace-pre [scrollbar-width:none] [&::-webkit-scrollbar]:hidden';

/**
 * Shared by every link to a documented symbol, in a type or in prose, so a reference looks the
 * same wherever it appears. Dotted rather than solid: these can be dense inside a type.
 */
const LINK =
  'underline decoration-dotted decoration-fd-primary/40 underline-offset-[3px] ' +
  'transition-colors hover:decoration-fd-primary';

/**
 * A stack of parameter rows: divided on a hairline, on whatever background they sit on.
 *
 * The same list whether it is captioned `parameters` inside a member card or headed
 * `Constructor Parameters` on a class page, because it is the same thing being read.
 */
const ROWS = '[&>*+*]:mt-3 [&>*+*]:border-t [&>*+*]:border-fd-border/60 [&>*+*]:pt-3';

const IDENT = /[A-Za-z_][A-Za-z0-9_]*/g;

/**
 * A default or assigned value.
 *
 * The `=` is its own dim glyph rather than part of the highlighted text: passing `= None` through
 * the syntax highlighter colours the equals sign as an operator, and it ends up competing with the
 * value it introduces.
 *
 * Its gap matches the row's, so the space either side of the `=` is equal. They are separate flex
 * containers, the row spacing the type from the default and this one spacing the `=` from the
 * value, and two different gaps meeting at the same glyph is visible as a lopsided `str  = ''`.
 */
function DefaultValue({ value }: { value: string }) {
  return (
    <span className="inline-flex shrink-0 items-baseline gap-1.5">
      <span className="font-mono text-xs text-fd-muted-foreground/50">=</span>
      <InlineCode code={value} className={CODE} />
    </span>
  );
}

/** A syntax-highlight token; if its text names a linkable type, wrap that name in a link. */
function TypeToken({
  children,
  links,
  ...rest
}: React.ComponentProps<'span'> & { links?: Links }) {
  if (typeof children === 'string' && links) {
    const nodes: React.ReactNode[] = [];
    let last = 0;
    let key = 0;
    let matched = false;

    for (const match of children.matchAll(IDENT)) {
      const href = links[match[0]];
      if (!href) continue;

      const start = match.index ?? 0;
      if (start > last) nodes.push(children.slice(last, start));
      nodes.push(
        <Link key={key++} href={href} className={LINK}>
          {match[0]}
        </Link>,
      );
      last = start + match[0].length;
      matched = true;
    }

    if (matched) {
      if (last < children.length) nodes.push(children.slice(last));
      return <span {...rest}>{nodes}</span>;
    }
  }

  return <span {...rest}>{children}</span>;
}

async function InlineCode({
  code,
  className,
  links,
}: {
  code?: string;
  className?: string;
  links?: Links;
}) {
  // the highlighter reads `.length` off whatever it is given, so nothing is the caller's job to
  // catch: a class with no constructor has no signature to highlight, and that is not an error
  if (!code) return null;

  // see the note at the top of the file: this cancels the host app's code-*block* gutter, which
  // would otherwise put 1rem of padding on each side of an inline type
  const flatten = { '--padding-left': '0px', '--padding-right': '0px' } as React.CSSProperties;

  return highlight(code, {
    lang: 'python',
    components: {
      pre: (props) => (
        <span
          {...props}
          style={{ ...props.style, ...flatten }}
          className={cn('not-prose', className, props.className)}
        />
      ),
      span: (props) => <TypeToken {...props} links={links} />,
    },
  });
}

/**
 * A name on the left, its type and default on the right, prose underneath.
 *
 * The shape every row on the page shares, whether a parameter, an attribute or a return, because
 * they are the same kind of thing: something named, something typed, something said about it.
 */
function Row({
  name,
  type,
  value,
  links,
  children,
}: {
  name?: React.ReactNode;
  type?: string;
  value?: string;
  links?: Links;
  children?: React.ReactNode;
}) {
  return (
    <>
      <div className="not-prose flex flex-wrap items-baseline gap-x-3 gap-y-1">
        {name}
        <span className={cn(SCROLL, 'ms-auto flex shrink items-baseline gap-1.5')}>
          {type && <InlineCode code={type} links={links} className={CODE} />}
          {value && <DefaultValue value={value} />}
        </span>
      </div>
      <div className="prose-no-margin mt-1.5 text-sm text-fd-muted-foreground empty:hidden">
        {children}
      </div>
    </>
  );
}

/**
 * A captioned group of rows inside a member card: `parameters`, `returns`.
 *
 * The caption is what a per-row tag used to be, said once. Rows divide on a hairline and sit on
 * the card's own background, so the list reads as part of the member rather than as a panel
 * dropped inside it.
 */
function Group({
  label,
  meta,
  children,
}: {
  label: string;
  /** Sits on the caption line, for a group whose subject is one thing rather than a list. */
  meta?: React.ReactNode;
  children?: React.ReactNode;
}) {
  return (
    /* `-mx-4 px-4` bleeds the rule to the card's edges. Inside the padding it reads as a line
       drawn in the text; across the card it reads as the card being divided, which is what a
       section boundary is. */
    <section className="-mx-4 mt-5 border-t border-fd-border px-4 pt-3">
      <div className="not-prose mb-2 flex flex-wrap items-baseline gap-x-3 gap-y-1">
        <h4 className={CAPTION}>{label}</h4>
        {meta}
      </div>
      <div className={ROWS}>{children}</div>
    </section>
  );
}

/*
 * A cross-reference to a documented type or member, written into prose by the CLI wherever a
 * docstring names one in backticks.
 *
 * Deliberately not an inline `code` element: the host app boxes those, and a boxed chip wrapped in
 * a link reads as a button sitting in the middle of a sentence. Monospace already says "this is an
 * identifier", so the link only has to add the underline.
 */
export function PdxRef({
  href,
  title,
  children,
}: {
  href: string;
  /** The full path, when the visible label was shortened to drop the module part. */
  title?: string;
  children?: React.ReactNode;
}) {
  return (
    <Link href={href} title={title} className={cn('font-mono text-[0.9em] text-fd-foreground', LINK)}>
      {children}
    </Link>
  );
}

/**
 * A documented function, method or class constructor.
 *
 * There is no header row of its own. The signature already says the name, so a name above it was
 * the same word twice and a kind beside it repeated the section heading the card sits under. The
 * signature is the header: a band across the top of the card, square where it meets the body and
 * following the card's radius at the corners.
 *
 * It is highlighted here rather than written into the page as a fenced block. A fenced block is a
 * figure with its own border, radius, shadow and copy button, which is right for an example in a
 * docstring and wrong for the thing being documented, and stripping that chrome from the outside is
 * a specificity fight won one property at a time. Highlighting it here is the same path every type
 * on the page already takes, and it leaves the box entirely ours.
 */
export function PdxFunction(props: {
  /** Not shown, since the signature carries it, but it names the card for a screen reader. */
  name: string;
  /** The `def` line, already wrapped by the CLI when it is too long for one. */
  definition?: string;
  children?: React.ReactNode;
}) {
  return (
    <figure aria-label={props.name} className={CARD}>
      {props.definition && (
        <div className={cn(SCROLL, 'border-b border-fd-border bg-fd-muted/40 px-4 py-3')}>
          <InlineCode code={props.definition} className="text-[13px]" />
        </div>
      )}
      <div className="prose-no-margin px-4 py-3.5 text-sm text-fd-muted-foreground empty:hidden">
        {props.children}
      </div>
    </figure>
  );
}

/**
 * Attributes render as one list, not a card each.
 *
 * An attribute is the same shape as a parameter, a name and a type and a default and a line about
 * it, and a card apiece turned a handful of one-liners into a column of boxes.
 *
 * The rounding lives here rather than on the rows because each row is preceded by its hidden
 * anchor heading, so `first:`/`last:` on a row would land on the heading instead. The wrapper has
 * no top border: the first row's own border draws it, which also keeps a doubled line off the top.
 *
 * Same surface as a member card, because an attribute is a member. What tells the two lists apart
 * is not the fill: an attribute row is padded to the box edges so its rule divides the whole
 * panel, while a parameter row is inset and its hairline stops short. Edge to edge reads as
 * separate members, inset reads as the parts of one thing.
 */
export function PdxAttributes({ children }: { children?: React.ReactNode }) {
  return (
    <div className="my-5 overflow-hidden rounded-lg border-x border-b border-fd-border bg-fd-card">
      {children}
    </div>
  );
}

/**
 * What you pass to build an instance.
 *
 * On a class page the constructor is not a member you look up, it is how the class is made, so its
 * parameters are headed by a section rather than shown as a `def __init__` card. They are still
 * parameters, so they read as they do inside one: rows on a hairline, on the card surface every
 * other group of rows sits on. What is missing compared to a member card is only the signature
 * header, because the heading above has already said what these belong to.
 */
export function PdxConstructor({ children }: { children?: React.ReactNode }) {
  return <div className={cn(CARD, 'px-4 py-3.5', ROWS)}>{children}</div>;
}

export function PdxAttribute(props: {
  name: string;
  type?: string;
  value?: string;
  links?: Links;
  children?: React.ReactNode;
}) {
  return (
    <div
      data-pdx-attribute=""
      className="relative border-t border-fd-border px-4 py-3 transition-colors hover:bg-fd-muted/40"
    >
      <Row
        name={<span className={NAME}>{props.name}</span>}
        type={props.type}
        value={props.value}
        links={props.links}
      >
        {props.children}
      </Row>
    </div>
  );
}

/** The `parameters` caption and the rows under it. */
export function PdxParameters({ children }: { children?: React.ReactNode }) {
  return <Group label="parameters">{children}</Group>;
}

export function PdxParameter(props: {
  name: string;
  type?: string;
  value?: string;
  links?: Links;
  children?: React.ReactNode;
}) {
  return (
    <div data-pdx-parameter="">
      <Row
        name={<span className={NAME}>{props.name}</span>}
        type={props.type}
        value={props.value}
        links={props.links}
      >
        {props.children}
      </Row>
    </div>
  );
}

export function PdxReturns({
  type,
  links,
  children,
}: {
  type?: string;
  links?: Links;
  children?: React.ReactNode;
}) {
  /*
   * The type keeps the right-hand column every other type on the card sits in, but on the
   * caption's own line rather than a row of its own. A return has no name to fill the left, so a
   * `Row` left it stranded a line below the word introducing it, with empty space between.
   */
  return (
    <Group
      label="returns"
      meta={
        <span className={cn(SCROLL, 'ms-auto font-mono text-xs')}>
          <InlineCode code={type ?? 'None'} links={links} />
        </span>
      }
    >
      <div className="prose-no-margin text-sm text-fd-muted-foreground empty:hidden">{children}</div>
    </Group>
  );
}

export function PdxSource({ children }: { children: React.ReactNode }) {
  return (
    <Collapsible className="mt-4">
      <CollapsibleTrigger className="group inline-flex items-center gap-1 rounded py-1 pe-2 text-xs text-fd-muted-foreground transition-colors hover:text-fd-foreground">
        <ChevronRight className="size-3.5 transition-transform duration-200 group-data-[state=open]:rotate-90" />
        source
      </CollapsibleTrigger>
      <CollapsibleContent className="prose-no-margin">{children}</CollapsibleContent>
    </Collapsible>
  );
}
